Fixes issue where database deployment required 2x runs due to wrong order

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -137,57 +137,6 @@ jobs:
             exit 1
           fi
 
-  database:
-    runs-on: ubuntu-latest
-    needs: validation
-
-    steps:
-      - name: configure aws credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-region: ${{ env.AWS_REGION }}
-          role-to-assume: arn:aws:iam::${{ needs.validation.outputs.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
-          role-session-name: ${{ vars.PROJECT_NAME }}-itm-${{ env.RC_ENV }}-database-deployment
-          role-duration-seconds: 3600
-          role-skip-session-tagging: true
-
-      - name: deploy database migrations for ${{ env.RC_ENV }}
-        ## TEMPORARY CHANGE TO AVOID DESTROYING DATA IN DB
-        if: ${{ env.RC_ENV != 'sandbox' }}
-        env:
-          VERSION: ${{ needs.validation.outputs.VERSION }}
-        run: |
-          [[ $VERSION =~ ^v[0-9]+(\.[0-9]+){2}$ ]] && rc_path="abods-itm/releases" || rc_path="abods-itm/releases-dev"
-
-          lambda_function_name="${{ vars.PROJECT_NAME }}-${RC_ENV}-pglifecycle-function"
-          cat <<EOF > $GITHUB_WORKSPACE/payload.json
-          {
-            "type": "run_migrations",
-            "authUser": "${{ vars.PROJECT_NAME }}_proxy_rw",
-            "targetDatabase": "${{ vars.PROJECT_NAME }}",
-            "databaseMigrations": {
-              "bucketName": "${RC_SRC}",
-              "bucketPrefix": "${rc_path}",
-              "releaseVersion": "${VERSION}"
-            }
-          }
-          EOF
-
-          openssl base64 -out $GITHUB_WORKSPACE/encoded_payload.json -in $GITHUB_WORKSPACE/payload.json 
-          response=$(aws lambda invoke --function-name $lambda_function_name --region $AWS_REGION --payload file://$GITHUB_WORKSPACE/encoded_payload.json response.txt 2>&1)
-          status_code=$(cat response.txt | jq -r '.statusCode')
-          status_code=${status_code:-"unset"}
-          echo "Status Code is: $status_code"
-          if [[ "$status_code" == "500" ]]; then
-            echo "[ERROR] Deployment of application component (DATABASE) with version ${VERSION} failed with error:"
-            echo "${response}"
-            exit 1
-          else
-            response_payload=$(cat response.txt)
-            echo "Response Payload: $response_payload"
-            echo "[INFO] Application component (DATABASE) with version ${VERSION} successfully deployed into ${RC_ENV^^}"
-          fi
-
   backend:
     runs-on: ubuntu-latest
     needs: validation
@@ -238,3 +187,55 @@ jobs:
             --tags "BuiltFrom=${VERSION} ProjectName=${{ vars.PROJECT_NAME }} Environment=${RC_ENV}"
 
           echo "[INFO] Application component (BACKEND) with version ${VERSION} successfully deployed into ${RC_ENV^^}"
+  
+  database:
+    runs-on: ubuntu-latest
+    needs: backend
+
+    steps:
+      - name: configure aws credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-region: ${{ env.AWS_REGION }}
+          role-to-assume: arn:aws:iam::${{ needs.validation.outputs.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
+          role-session-name: ${{ vars.PROJECT_NAME }}-itm-${{ env.RC_ENV }}-database-deployment
+          role-duration-seconds: 3600
+          role-skip-session-tagging: true
+
+      - name: deploy database migrations for ${{ env.RC_ENV }}
+        ## TEMPORARY CHANGE TO AVOID DESTROYING DATA IN DB
+        if: ${{ env.RC_ENV != 'sandbox' }}
+        env:
+          VERSION: ${{ needs.validation.outputs.VERSION }}
+        run: |
+          [[ $VERSION =~ ^v[0-9]+(\.[0-9]+){2}$ ]] && rc_path="abods-itm/releases" || rc_path="abods-itm/releases-dev"
+
+          lambda_function_name="${{ vars.PROJECT_NAME }}-${RC_ENV}-pglifecycle-function"
+          cat <<EOF > $GITHUB_WORKSPACE/payload.json
+          {
+            "type": "run_migrations",
+            "authUser": "${{ vars.PROJECT_NAME }}_proxy_rw",
+            "targetDatabase": "${{ vars.PROJECT_NAME }}",
+            "databaseMigrations": {
+              "bucketName": "${RC_SRC}",
+              "bucketPrefix": "${rc_path}",
+              "releaseVersion": "${VERSION}"
+            }
+          }
+          EOF
+
+          openssl base64 -out $GITHUB_WORKSPACE/encoded_payload.json -in $GITHUB_WORKSPACE/payload.json 
+          response=$(aws lambda invoke --function-name $lambda_function_name --region $AWS_REGION --payload file://$GITHUB_WORKSPACE/encoded_payload.json response.txt 2>&1)
+          status_code=$(cat response.txt | jq -r '.statusCode')
+          status_code=${status_code:-"unset"}
+          echo "Status Code is: $status_code"
+          if [[ "$status_code" == "500" ]]; then
+            echo "[ERROR] Deployment of application component (DATABASE) with version ${VERSION} failed with error:"
+            echo "${response}"
+            exit 1
+          else
+            response_payload=$(cat response.txt)
+            echo "Response Payload: $response_payload"
+            echo "[INFO] Application component (DATABASE) with version ${VERSION} successfully deployed into ${RC_ENV^^}"
+          fi
+  
