Updates to modify-db

diff --git a/.github/workflows/modify-db.yml b/.github/workflows/modify-db.yml
--- a/.github/workflows/modify-db.yml
+++ b/.github/workflows/modify-db.yml
@@ -33,7 +33,7 @@ env:
     github.ref_name == 'test' && 'test' ||
     github.ref_name == 'uat' && 'uat' ||
     github.ref_name == 'dev' && 'dev' || 'sandbox' }}
-  DEPLOY_SRC_PREFIX: ${{ vars.DEPLOYMENT_ARTEFACTS_S3_BUCKET_PREFIX }}
+  DEPLOY_SRC: ${{ vars.DEPLOYMENT_ARTEFACTS_S3_BUCKET }}
   DEPLOY_VER: ${{ github.ref_name != 'main' && github.ref_name || 'null' }}
 
 jobs:
@@ -42,6 +42,7 @@ jobs:
     environment:
       ${{ (github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/v')) && 'prod' ||
       github.ref_name == 'test' && 'test' ||
+      github.ref_name == 'cavl' && 'cavl' ||
       github.ref_name == 'uat' && 'uat' ||
       github.ref_name == 'dev' && 'dev' || 'sandbox' }}
     outputs:
@@ -50,11 +51,22 @@ jobs:
       REMOTE_DB_HOSTNAME: ${{ steps.set-vars.outputs.REMOTE_DB_HOSTNAME }}
       VERSION: ${{ steps.verify.outputs.VERSION }}
 
+    permissions:
+      id-token: write
+      contents: read
+
     steps:
+      - name: configure aws credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-region: ${{ env.AWS_REGION }}
+          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
+          role-session-name: ${{ vars.PROJECT_NAME }}-${{ env.RC_ENV }}-database-modification-validation
+          role-duration-seconds: 3600
+          role-skip-session-tagging: true
+
       - name: validate job parameters
         id: verify
-        env:
-          DEPLOY_SRC: ${{ env.DEPLOY_SRC_PREFIX }}-${{ vars.AWS_ACCOUNT_ID }}
         run: |
           get_latest_version() {
             local bucket_name=$1
@@ -84,7 +96,7 @@ jobs:
               echo "VERSION=${DEPLOY_VER//\//-}" >> "$GITHUB_OUTPUT"
             else
               echo [INFO] Deploying from main branch. Using latest tagged version
-              latest_version=$(get_latest_version $DEPLOY_SRC 'releases/itm')
+              latest_version=$(get_latest_version $DEPLOY_SRC 'abods-itm/releases')
               echo """ \
                 Modifying backend database using parameters:
                   (Database Action)        - $DEPLOY_ACT
@@ -108,6 +120,21 @@ jobs:
           echo "REMOTE_DB_HOST_ID=${{ vars.REMOTE_DB_HOST_ID }}" >> $GITHUB_OUTPUT
           echo "REMOTE_DB_HOSTNAME=${{ vars.REMOTE_DB_HOSTNAME }}" >> $GITHUB_OUTPUT
 
+      - name: validate release candidate version
+        env:
+          VERSION: ${{ steps.verify.outputs.VERSION }}
+        run: |
+          [[ $VERSION =~ ^v[0-9]+(\.[0-9]+){2}$ ]] && rc_path="$RC_SRC/abods-itm/releases/$VERSION" || rc_path="$RC_SRC/abods-itm/releases-dev/$VERSION"
+
+          rc_database_path="$rc_path/liquibase"
+
+          if [[ `aws s3 ls s3://$rc_database_path|head` ]]; then
+            echo "[INFO] Release candidate version [${VERSION}] for component (DATABASE) successfully validated"
+          else
+            echo "[ERROR] Release candidate version [${VERSION}] does not exist for component (DATABASE). Exiting"
+            exit 1
+          fi
+
   database:
     runs-on: ubuntu-latest
     needs: validation
@@ -122,7 +149,7 @@ jobs:
         with:
           aws-region: ${{ env.AWS_REGION }}
           role-to-assume: arn:aws:iam::${{ needs.validation.outputs.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
-          role-session-name: ${{ env.DEPLOY_ENV }}-database-modification
+          role-session-name: ${{ vars.PROJECT_NAME }}-${{ env.RC_ENV }}-database-modification
           role-duration-seconds: 3600
           role-skip-session-tagging: true
 
@@ -256,10 +283,9 @@ jobs:
       - name: run database migrations against ${{ env.DEPLOY_ENV }}
         if: ${{ env.DEPLOY_ACT == 'run-migrations' || env.DEPLOY_ACT == 'refresh' }}
         env:
-          DEPLOY_SRC: ${{ env.DEPLOY_SRC_PREFIX }}-${{ needs.validation.outputs.AWS_ACCOUNT_ID }}
           VERSION: ${{ needs.validation.outputs.VERSION }}
         run: |
-          [[ $VERSION =~ ^v[0-9]+(\.[0-9]+){2}$ ]] && rc_path="releases/itm" || rc_path="releases-dev/itm"
+          [[ $VERSION =~ ^v[0-9]+(\.[0-9]+){2}$ ]] && rc_path="abods-itm/releases" || rc_path="abods-itm/releases-dev"
           lambda_function_name="${{ vars.PROJECT_NAME }}-${DEPLOY_ENV}-pglifecycle-function"
           cat <<EOF > $GITHUB_WORKSPACE/payload.json
           {
