Include validation steps

diff --git a/.github/workflows/modify-db.yml b/.github/workflows/modify-db.yml
--- a/.github/workflows/modify-db.yml
+++ b/.github/workflows/modify-db.yml
@@ -55,6 +55,15 @@ jobs:
       VERSION: ${{ steps.verify.outputs.VERSION }}
 
     steps:
+      - name: configure aws credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-region: ${{ env.AWS_REGION }}
+          role-to-assume: arn:aws:iam::${{ needs.validation.outputs.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
+          role-session-name: ${{ env.DEPLOY_ENV }}-database-modification-validation
+          role-duration-seconds: 3600
+          role-skip-session-tagging: true
+
       - name: validate job parameters
         id: verify
         run: |
@@ -109,6 +118,21 @@ jobs:
           echo "AWS_ACCOUNT_ID=${{ vars.AWS_ACCOUNT_ID }}" >> $GITHUB_OUTPUT
           echo "REMOTE_DB_HOST_ID=${{ vars.REMOTE_DB_HOST_ID }}" >> $GITHUB_OUTPUT
           echo "REMOTE_DB_HOSTNAME=${{ vars.REMOTE_DB_HOSTNAME }}" >> $GITHUB_OUTPUT
+
+      - name: validate release candidate version
+        env:
+          VERSION: ${{ steps.verify.outputs.VERSION }}
+        run: |
+          [[ $VERSION =~ ^v[0-9]+(\.[0-9]+){2}$ ]] && rc_path="$RC_SRC/abods-itm/releases/$VERSION" || rc_path="$RC_SRC/abods-itm/releases-dev/$VERSION"
+
+          rc_database_path="$rc_path/liquibase"
+
+          if [[ `aws s3 ls s3://$rc_database_path|head` ]]; then
+            echo "[INFO] Release candidate version [${VERSION}] for component (DATABASE) successfully validated"
+          else
+            echo "[ERROR] Release candidate version [${VERSION}] does not exist for component (DATABASE). Exiting"
+            exit 1
+          fi
 
   database:
     runs-on: ubuntu-latest
